name: Polaris Bridge CLI Scan

on:
  push:
    branches: [main, master, develop, stage, release]
  pull_request:
    branches: [main, master, develop, stage, release]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  security-events: write

jobs:
  polaris:
    runs-on: windows-latest
    env:
      BRIDGE_POLARIS_SERVERURL: https://poc.polaris.blackduck.com/
      BRIDGE_POLARIS_ACCESSTOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}
      BRIDGE_POLARIS_ASSESSMENT_TYPES: SAST,SCA
      BRIDGE_POLARIS_APPLICATION_NAME: ${{ github.event.repository.name }}
      BRIDGE_POLARIS_PROJECT_NAME: ${{ github.event.repository.name }}
      BRIDGE_POLARIS_BRANCH_NAME: ${{ github.ref_name }}
      BRIDGE_POLARIS_REPORTS_SARIF_CREATE: true
      BRIDGE_POLARIS_REPORTS_SARIF_UPLOAD: true
      BRIDGE_POLARIS_WAITFORSCAN: true
      BRIDGE_POLARIS_ONBOARDING: false
      BRIDGE_GITHUB_USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Debug:List Source Files
        shell: pwsh
        run: Get-ChildItem -Recurse

      - name: Download & Setup Bridge CLI
        shell: pwsh
        run: |
          $url = "https://repo.blackduck.com/bds-integrations-release/com/blackduck/integration/bridge/binaries/bridge-cli-bundle/latest/bridge-cli-bundle-win64.zip"
          $zipPath = "$env:RUNNER_TEMP\bridge.zip"
          $extractPath = "$env:RUNNER_TEMP\bridge"
          Invoke-WebRequest $url -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $extractPath
          $exePath = Get-ChildItem -Recurse -File $extractPath -Filter bridge-cli.exe | Select-Object -First 1
          echo "BRIDGE_CLI_INSTALL_DIR=$($exePath.FullName)" | Out-File -Append -FilePath $env:GITHUB_ENV

      - name: Polaris Full Scan
        if: ${{ github.event_name != 'pull_request' }}
        shell: pwsh
        run: |
          & "${env:BRIDGE_CLI_INSTALL_DIR}" --stage polaris --diagnostics

      - name: Polaris PR Scan
        if: ${{ github.event_name == 'pull_request' }}
        shell: pwsh
        run: |
          & "${env:BRIDGE_CLI_INSTALL_DIR}" --stage polaris --diagnostics `
            polaris.prcomment.enabled=true `
            polaris.branch.parent.name=${{ github.event.base_ref }} `
            github.repository.branch.name=${{ github.ref_name }} `
            github.repository.name=${{ github.event.repository.name }} `
            github.repository.owner.name=${{ github.repository_owner }} `
            github.repository.pull.number=${{ github.event.number }}

      # Optional: Save logs
      # - name: Save Logs
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: bridge-logs
      #     path: ${{ github.workspace }}\.bridge
