name: Self-Hosted SARIF Upload Test

on:
  workflow_dispatch:

jobs:
  upload-sarif:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Simulate SARIF file creation
      run: |
        mkdir -p ".bridge/Dynamic Folder With Spaces"
        echo '{"version": "2.1.0", "runs": []}' > ".bridge/Dynamic Folder With Spaces/report.sarif.json"

    - name: List SARIF files
      run: find .bridge -type f -name "*.sarif*" -print

    # ✅ Fallback: Move SARIF file to known location
    - name: Move SARIF file to known location
      run: |
        mkdir -p sarif-out
        find .bridge -type f -name "*.sarif*" -exec cp {} sarif-out/ \;
        echo "Contents of sarif-out:"
        ls -l sarif-out

    # ✅ Upload from known location
    - name: Upload SARIF Files (fallback)
      uses: actions/upload-artifact@v4
      with:
        name: polaris-sarif-fallback
        path: sarif-out/*.sarif*

    # 🔁 Multiple glob pattern attempts
    - name: Upload SARIF Files 1
      uses: actions/upload-artifact@v4
      with:
        name: polaris-sarif-1
        path: ".bridge/**/*.sarif*"

    - name: Upload SARIF Files 2
      uses: actions/upload-artifact@v4
      with:
        name: polaris-sarif-2
        path: ".bridge/*/*.sarif*"

    - name: Upload SARIF Files 3
      uses: actions/upload-artifact@v4
      with:
        name: polaris-sarif-3
        path: ".bridge/**/**/*.sarif*"

    - name: Upload SARIF Files 4
      uses: actions/upload-artifact@v4
      with:
        name: polaris-sarif-4
        path: ".bridge/**/**/**/*.sarif*"

    - name: Upload SARIF Files 5
      uses: actions/upload-artifact@v4
      with:
        name: polaris-sarif-5
        path: ".bridge/**/*.json"

    - name: Upload SARIF Files 6
      uses: actions/upload-artifact@v4
      with:
        name: polaris-sarif-6
        path: ".bridge/*/*.json"

    - name: Upload SARIF Files 7
      uses: actions/upload-artifact@v4
      with:
        name: polaris-sarif-7
        path: ".bridge/**/*"

    - name: Upload SARIF Files 8
      uses: actions/upload-artifact@v4
      with:
        name: polaris-sarif-8
        path: ".bridge/"

    - name: Upload SARIF Files 9
      uses: actions/upload-artifact@v4
      with:
        name: polaris-sarif-9
        path: "**/*.sarif*"

    - name: Upload SARIF Files 10
      uses: actions/upload-artifact@v4
      with:
        name: polaris-sarif-10
        path: "**/*.json"
